import { CellType } from "./types";

export const mockData: CellType[] = [
    {
        id: 1,
        title: "date",
        name: "date",
        value: "30 января 2024",
        type: "text",
    },
    {
        id: 2,
        title: "shift",
        name: "shift",
        value: "Смена 2",
        type: "text",
    },
    {
        id: 3,
        title: "Мастер:",
        name: "master",
        value: "Иванов И.И.",
        type: "string",
    },
    {
        id: 4,
        title: "title",
        name: "title",
        value: "РПТКМ-120",
        type: "text",
    },
    {
        id: 5,
        title: "personnel",
        name: "personnel",
        value: "Персонал",
        type: "string",
    },
    {
        id: 6,
        title: "population",
        name: "population",
        value: "100500 человек",
        type: "text",
    },
    {
        id: 7,
        title: "comment",
        name: "comment",
        value: "Комментарий в 3-5 строчек, который тоже можно редактировать.",
        type: "text",
    },
    {
        id: 8,
        title: "substation",
        name: "substation",
        value: "КТП 2000 321",
        type: "text",
    },
    {
        id: 9,
        title: "statusJob",
        name: "statusJob",
        value: "Работает",
        type: "string",
    },
    {
        id: 10,
        title: "numberValue",
        name: "numberValue",
        value: 24,
        type: "number",
    },
    {
        id: 11,
        title: "spi",
        name: "spi",
        value: "SPI 3432",
        type: "text",
    },
    {
        id: 12,
        title: "kptValue",
        name: "kptValuePercent",
        value: "98.4%",
        type: "percent",
    },
    {
        id: 13,
        title: "kptStatus",
        name: "kptStatus",
        value: "Функционирует, но не бьет",
        type: "string",
    },
];
